config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'

  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'
  
  resource :dashboard, only: [:show]
  
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: [:create]
  end
  
  resources :lessons, only: [:show]
  
  namespace :instructor do
    resources :lessons, only: [:update]

    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
    
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end

  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: [:show]
  before_action :require_authorized_for_course, only: [:show]
  
  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @section = Section.new
    @lesson = Lesson.new
  end

  private #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  def set_course
    @course ||= Course.find(params[:id])
  end

  def require_authorized_for_course
    if @course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lesson, only: [:update]
  before_action :set_section, only: [:create]
  before_action :require_authorized_for_section, only: [:create]
  before_action :require_authorized_for_lesson, only: [:update]

  def create
    @lesson = @section.lessons.create(lesson_params)

    if @lesson.valid?
      redirect_to instructor_course_path(@section.course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @lesson.update_attributes(lesson_params)
    render plain: 'updated!'
  end

  private #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  def require_authorized_for_section
    if @section.course.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def require_authorized_for_lesson
    if @lesson.section.course.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end
  
  def set_section
    # memoize @section to reduce calls to db from new->create
    @section ||= Section.find(params[:section_id])
  end

  def set_lesson
    @lesson ||= Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end
end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_section, only: [:update]
  before_action :set_course, only: [:create]
  before_action :require_authorized_for_course, only: [:create]
  before_action :require_authorized_for_section, only: [:update]

  def create
    @section = @course.sections.create(section_params)
    redirect_to instructor_course_path(@course)
  end

  def update
    @section.update_attributes(section_params)
    render plain: "updated!"
  end

  private #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  def require_authorized_for_course
    if @course.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def require_authorized_for_section
    if @section.course.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def set_course
    # memoize @course to reduce db calls from new->create
    @course ||= Course.find(params[:course_id])
  end

  def set_section
    @section ||= Section.find(params[:id])
  end

  def section_params
    params.require(:section).permit(:title, :row_order_position)
  end
  
end

app/helpers/courses_helper.rb
module CoursesHelper

  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/views/instructor/courses/new.html.erb
<div class="col-10 offset-1">
  <div class="booyah-box">
    <h1>Add a new course</h1>
    <%= simple_form_for @course, url: instructor_courses_path do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :cost %>
      <%= f.input :image %>
      <br/>
      <%= f.submit 'Create', class: 'btn btn-warning' %>
    <% end %>
    <br/>
  </div>
</div>

app/views/instructor/courses/show.html.erb
<div class="col-10 offset-1">

  <div class="booyah-box">
    <h1 class="text-center"><%= @course.title %></h1>
    <% if @course.image.file %>
      <div class="course-image">
        <%= image_tag @course.image.to_s, class: 'img-fluid img-h-100' %>
      </div>
    <% end %>

    <br/>

    <div class="row">
      <div class="col-sm-8 col-12 mb-3">
        <%= @course.description %>
      </div>
      <div class="col-sm-4 col-12 border-left">
        <div class="text-center">
          <%= link_to 'Preview as student...', course_path(@course), class: 'btn btn-light w-100 mb-2' %>
        </div>

        <div class="text-center">
          <!-- New Section Modal Button -->
          <button type="button" class="btn btn-warning w-100" data-toggle="modal" data-target="#newSectionModal">
            Add a new section...
          </button>
        </div>
      </div>
    </div>

    <br class="clr"/>

    <div class="container mt-3">
      <ul class="sections">
        <% @course.sections.rank(:row_order).each do |section| %>
          <li data-update-url="<%= instructor_section_path(section) %>" class="booyah-box section section-li">
            <div class="header">
              <i class="fa fa-reorder"></i>
              <%= section.title %>
              <!-- New Section Modal Button -->
              <button type="button" class="float-right btn btn-warning btn-sm new-lesson-button" data-toggle="modal" data-target="#newLessonModal" data-lesson-url="<%= instructor_section_lessons_path(section) %>">
                Add lesson...
              </button>
              <br class="clr"/>
            </div>
            <ul class="lessons">
              <% section.lessons.rank(:row_order).each do |lesson| %>
                <li data-update-url="<%= instructor_lesson_path(lesson) %>" class="booyah-box lesson-li">
                  <div class="row">
                    <div class="col-1 lesson-handle">
                      <i class="fa fa-reorder fa-lg" aria-hidden="true"></i>
                    </div>
                    <div class="col-11 text-center">
                      <p>
                        <b><%= lesson.title %></b>
                      </p>
                      <hr/>
                      <p>
                        <%= lesson.subtitle %>
                      </p>
                    </div>
                  </div>
                  <%# <br class="clr"/> %>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
      <br class="clr"/>
    </div>
  </div>

</div>

<!-- New Section Modal -->
<div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="newSectionModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newSectionModalLabel">Add a new section</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for @section, url: instructor_course_sections_path(@course) do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
          <%= f.submit 'Add section', class: 'btn btn-warning' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- New Lesson Modal -->
<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="newLessonModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newLessonModalLabel">Add a new lesson</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for @lesson, url: '#', html: {id: 'newLessonForm' } do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
          <%= f.input :subtitle %>
          <%= f.input :video %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
          <%= f.submit 'Add lesson', class: 'btn btn-warning' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(function() {
    $('.new-lesson-button').click(function( event ) {
      var lessonUrl = $(event.target).data('lesson-url');
      $('#newLessonForm').attr('action', lessonUrl);
    });

    $('.lessons').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { lesson: { row_order_position: ui.item.index() } }
        });
      }
    });

    $('.sections').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { section: { row_order_position: ui.item.index() } }
        });
      }
    });
  });
</script>