config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'

  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'
  
  resource :dashboard, only: [:show]
  
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: [:create]
  end
  
  resources :lessons, only: [:show]
  
  namespace :instructor do
    resources :lessons, only: [:update]

    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
    
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end

  end

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
  validates :title, presence: true
  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :row_order, with_same: :section_id

  def next_lesson
    next_lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if next_lesson.blank? && section.next_section.present?
      return section.next_section.lessons.rank(:row_order).first
    end
    return next_lesson
  end
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lesson, only: [:update]
  before_action :set_section, only: [:create]
  before_action :require_authorized_for_section, only: [:create]
  before_action :require_authorized_for_lesson, only: [:update]

  def create
    @lesson = @section.lessons.create(lesson_params)

    if @lesson.valid?
      redirect_to instructor_course_path(@section.course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @lesson.update_attributes(lesson_params)
    render plain: 'updated!'
  end

  private #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  def require_authorized_for_section
    if @section.course.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def require_authorized_for_lesson
    if @lesson.section.course.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end
  
  def set_section
    # memoize @section to reduce calls to db from new->create
    @section ||= Section.find(params[:section_id])
  end

  def set_lesson
    @lesson ||= Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :ensure_user_is_enrolled, only: [:show]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  private #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      # memoize @lesson to reduce database between new->create
      @lesson ||= Lesson.find(params[:id])
    end

    def ensure_user_is_enrolled
      unless current_user.enrolled_in?(@lesson.section.course)
        redirect_to course_path(@lesson.section.course), alert: "You must enroll in a course to view the lessons."
      end
    end
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= simple_form_for(@lesson) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :subtitle %>
    <%= f.input :section_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lessons</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Section</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.title %></td>
        <td><%= lesson.subtitle %></td>
        <td><%= lesson.section_id %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<br />

<div class="col-10 offset-1">
  <div class="booyah-box">
    <h1><%= @lesson.title %></h1>
    <h5 class="float-left"><%= @lesson.subtitle %></h5>

    <% if @lesson.next_lesson.present? %>
      <%= link_to lesson_path(@lesson.next_lesson), class: 'btn btn-warning float-right' do %>
        Next lesson &nbsp;
        <i class="fa fa-forward"></i>
      <% end %>
    <% end %>

    <br class="clear"/>
    <br/>
    <video id='my-video' class='video-js vjs-big-play-centered vjs-fluid' controls preload='auto' poster='<%= image_path('black.jpg') %>' data-setup='{}'>
      <source src='<%= @lesson.video.to_s %>' type='video/mp4'>
      <noscript>
        <p class='vjs-no-js'>
          To view this video please enable JavaScript, and consider upgrading to a web browser that
          <a href='https://videojs.com/html5-video-support/' target='_blank'>supports HTML5 video</a>
        </p>
      </noscript>
    </video>
  </div>
</div>