config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'

  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'
  
  resource :dashboard, only: [:show]
  
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: [:create]
  end
  
  resources :lessons, only: [:show]
  
  namespace :instructor do
    resources :lessons, only: [:update]

    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
    
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  has_many :sections
  has_many :enrollments

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def free?
    cost.zero?
  end

  def premium?
    !free?
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
  validates :title, presence: true
  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :row_order, with_same: :section_id

  def next_lesson
    next_lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if next_lesson.blank? && section.next_section.present?
      return section.next_section.lessons.rank(:row_order).first
    end
    return next_lesson
  end
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :lessons
  attr_reader :number_of_lessons

  include RankedModel
  ranks :row_order, with_same: :course_id

  def number_of_lessons
    lessons.count
  end

  def next_section
    next_section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
    return next_section
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def enrolled_in?(course)
    enrolled_courses.include?(course)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  
  def show
    
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!, :set_course
  
  def create
    if @course.premium?
      # Amount in cents
      @amount = (@course.cost * 100).to_i

      # Stripe
      Stripe.api_key = ENV['STRIPE_SECRET_KEY']
      
      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )
      
      charge = Stripe::Charge.create(
        customer: customer.id,
        amount: @amount,
        description: 'Flixter Premium Content',
        currency: 'usd'
      )
    end
    
    current_user.enrollments.create(course: @course)
    redirect_to course_path(@course)
  rescue Stripe::CardError => error
    flash[:error] = error.message
    redirect_to course_path(@course)
  end

  private #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  def set_course
    @course ||= Course.find(params[:course_id])
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :ensure_user_is_enrolled, only: [:show]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  private #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      # memoize @lesson to reduce database between new->create
      @lesson ||= Lesson.find(params[:id])
    end

    def ensure_user_is_enrolled
      unless current_user.enrolled_in?(@lesson.section.course)
        redirect_to course_path(@lesson.section.course), alert: "You must enroll in a course to view the lessons."
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
  
  def team
  end

  def careers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper

  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flixter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://vjs.zencdn.net/7.6.0/video-js.css" rel="stylesheet">
  </head>

  <body>
    <div id="content">
      <nav class="navbar navbar-expand-sm sticky-top navbar-dark bg-dark">
        <%= link_to 'Flixter', root_path, class: 'navbar-brand' %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#linkToggles" aria-controls="linkToggles" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="linkToggles">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'See All Courses', courses_path, class: 'nav-link' %>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to dashboard_path, class: 'nav-link' do %>
                  <i class="fa fa-user-circle" aria-hidden="true"></i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
                  Log Out <i class="fa fa-sign-out" aria-hidden="true"></i>
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link' do %>
                  Log In <i class="fa fa-sign-in" aria-hidden="true"></i>
                <% end %>          
              </li>
            <% end %>
            </li>
          </ul>
        </div>
      </nav>

      <%= yield %>

      <div class="notice-box">
        <% if notice.present? %>
          <div class="alert alert-warning col-8 offset-2"><%= notice %></div>
        <% end %>
        <% if alert.present? %>
          <div class="alert alert-danger col-8 offset-2"><%= alert %></div>
        <% end %>
      </div>
    </div>

    <div id="footer">
      <div class="container h-100 p-3">
        <div class="row">
          <div class="col-12 col-sm-6 col-md-3 mt-2">
            <b>Teachers</b>
            <br/>
            <%= link_to 'Teach a Course', new_instructor_course_path %>
            <br/>
            <%= link_to 'View Dashboard', dashboard_path %>
          </div>
          <div class="col-12 col-sm-6 col-md-3 mt-2">
            <b>About</b>
            <br/>
            <%= link_to 'Team', team_path %>
            <br/>
            <%= link_to 'Careers', careers_path %>
          </div>
          <div class="col-12 col-sm-6 col-md-3 mt-2">
            <b>Contact</b>
            <br/>
            <%= link_to 'Email Us', 'mailto:iaminaband@gmail.com' %>
            <br/>
            <span>Phoenix, AZ</span>
          </div>
          <div class="col-12 col-sm-6 col-md-3 mt-2">
            <small class="text-light font-italic">
              A site coded by 
              <a href="https://github.com/jmoglesby" target="_blank">
                <i class="fa fa-github fa-lg" aria-hidden="true"></i> jmoglesby
              </a>
            </small>
          </div>
        </div>
      </div>
    </div>

    <script src='https://vjs.zencdn.net/7.6.0/video.js'></script>
    <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
  </body>
</html>